nome=input('inserisci il tuo nome ' )
età= input('inserisci la tua età ')
DoveVivi=input('inserisci la città in cui abiti ')
Fam=input('inserisci il numero di persone nella tua famiglia ')
print(" ciao " + nome + " hai " + età+ " anni "  + " vivi a " + DoveVivi + " nella tua famiglia siete " + Fam )
